show databases;
create database d;
use d;
show tables;
show columns from products;
describe products;
show status;
show create database d;
show create table customers;
show grants;
show engines;
show errors;
show warnings;
# help show ;
